opciones_FE:
  - tratamiento_outliers:
      IQR: True
      columnas:
        - Incremento_hombres
        - Incremento_mujeres

  - agrupa:
      valor: Sexo

regiones:
  - nombre: Norte
    estados:
      - Baja California
      - Baja California Sur
      - Chihuahua
      - Coahuila
      - Durango
      - Nuevo León
      - Sinaloa
      - Sonora
      - Tamaulipas
      

  - nombre: Occidente
    estados:
      - Aguascalientes
      - Colima
      - Guanajuato
      - Jalisco
      - Michoacán
      - Nayarit
      - San Luis Potosí
      - Zacatecas

  - nombre: Centro
    estados:
      - Ciudad de México
      - Hidalgo
      - México
      - Morelos
      - Puebla
      - Querétaro
      - Tlaxcala

  - nombre: Sureste
    estados:
      - Campeche
      - Chiapas
      - Guerrero
      - Oaxaca
      - Quintana Roo
      - Tabasco
      - Veracruz
      - Yucatán
      
      

