param_grid_prophet:
  seasonality_mode:
    - additive
    - multiplicative
  changepoint_prior_scale:
    - 0.05
    - 0.1
    - 0.5
  seasonality_prior_scale:
    - 0.25
    - 1.0
    - 5.0


FECHA_CORTE_ENTRENAMIENTO: "2025-01-01"
TS_SPLITS: 3
TEST_SIZE: 12


peridos_atipicos:
  - holiday: pandemia_covid
    ds: "2020-03-23"
    lower_window: 0
    upper_window: 913  # dias impacto pandemia 2.5 * 365.25

  - holiday: atipico_2016
    ds: "2016-05-16"
    lower_window: 0
    upper_window: 182

mapeo_columnas:
  incrementos_hombres: hombres 
  incrementos_mujeres: mujeres
  incrementos_total: general

regiones_INEGI:
  - 'Urbana media'
  - 'Sur-Sureste vulnerable'
  - 'Metropolitana alta'
  - 'Rural / dispersa'

valores_sexo:
  - incrementos_hombres
  - incrementos_mujeres
  - incrementos_total
