padecimiento:
  columna: "Padecimiento"
  tipo: "General"                  # General, Depresión, Parkinson, Alzheimer
  force: true                      # Sobrescribe el filtrado previo
  reporte: false                   # Genera reporte de filtrado
  reporte_clean: false             # Genera reporte de datos tratados
  modelado_estados: True           # Genera modelos por estados (true) o región (false)
  entrena_modelo: False             # Entrena modelo final con todo el dataset

inegi:
  force: false                      # Sobrescribe el archivo INEGI aunque ya exista

prediccion:
  periodo: 120                       # Semanas a predecir por modelo